version: "2.1"

services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr
    depends_on:
      - jackett
    environment:
      - "LOG_LEVEL=info"
    network_mode: service:jackett
    restart: no
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
