version: "2.1"

services:

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
    #ports:
    #    - 5055:5055
    volumes:
        - "${DATA_PATH}/jellyseerr:/app/config"
    restart: unless-stopped
    env_file:
      - ../envs/base.env

  #-------------------------------------------------

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.5
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=https://jellyfin.orochi.chst.dev
    volumes:
      - "${DATA_PATH}/jellyfin:/config"
      - "${DATA_PATH}/files/tv:/data/tvshows"
      - "${DATA_PATH}/files/movies:/data/movies"
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
      - 8096:8096/tcp
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
    env_file:
      - ../envs/base.env

networks:
  default:
    name: lsio
    external: true
